 version: '3.8'
 networks:
  devaten-oracle-agent:
    name: devaten-oracle-agent
    
 services:
 
   onpremise-oracleagent-container:
     image: devaten/on-premises-oracle-agent
     container_name: onpremise-oracleagent-container
     restart: unless-stopped
     ports:
       - "8116:8116"
     environment:
       - spring.activemq.broker-url=tcp://127.0.0.1:61616
     volumes:
       - ./h2:/opt/h2-data:rw
     networks:
       - devaten-oracle-agent
